services:
  - type: web
    name: vedzeb-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_4XgiFf5HuQsS@ep-nameless-night-ah3ei8ri-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        value: vedzeb-secret-2024
      - key: NODE_ENV
        value: production
